### ISSUE TITLE
module has no exports

### ISSUE THREAD

**Issue by ertugrul013** [cuongdevjs/reactjs-social-login#36] opened 2022-02-08 22:14 UTC
This is the error I am getting 
`export 'default' (imported as 'LoginSocialLinkedin') was not found in 'reactjs-social-login' (module has no exports)`
![image](https://user-images.githubusercontent.com/27867101/153084544-7fd0023d-62c0-4829-bae1-27b51935a4d4.png)

can anybody point me in the right direction on how to fix this?

**Comment by cuongdevjs** [comment] 2022-02-09 03:52
You should downgrade version react-script to "4.0.0"
It will be work.

**Comment by cuongdevjs** [comment] 2022-02-09 04:01
Let me know if you still facing any troubles.

**Comment by sabipu** [comment] 2022-02-16 07:45
@cuongdevjs How do I fix the issue without downgrading react-scripts version?

I want to use the benefit of react-scripts 5.0.0.

**Comment by anver** [comment] 2022-02-16 10:01
I get the same error and I'm not using react-scripts

```ts
WARNING in ./src/pages/destinations/ModalFbPermissions.tsx 18:1111-1130
export 'LoginSocialFacebook' (imported as 'LoginSocialFacebook') was not found in 'reactjs-social-login' (module has no exports)
```
my dependencies

```js
 "devDependencies": {
    "@babel/core": "^7.13.8",
    "@babel/preset-env": "^7.13.9",
    "@babel/preset-react": "^7.12.13",
    "@babel/preset-typescript": "^7.13.0",
    "@storybook/addon-actions": "^6.4.18",
    "@storybook/addon-essentials": "^6.4.18",
    "@storybook/addon-links": "^6.4.18",
    "@storybook/react": "^6.4.18",
    "@types/node": "^17.0.14",
    "@types/object-assign": "^4.0.30",
    "@types/react": "^17.0.2",
    "@types/react-bootstrap": "^0.32.29",
    "@types/react-dom": "^17.0.1",
    "@types/webpack": "^5.28.0",
    "@types/webpack-bundle-analyzer": "^4.4.1",
    "@types/webpack-dev-server": "^4.7.2",
    "babel-loader": "^8.2.2",
    "cross-env": "^7.0.3",
    "css-loader": "^5.1.1",
    "css-minimizer-webpack-plugin": "^3.4.1",
    "esbuild": "^0.14.16",
    "esbuild-loader": "^2.18.0",
    "esbuild-sass-plugin": "^2.2.1",
    "file-loader": "^6.2.0",
    "html-webpack-injector": "^1.1.4",
    "html-webpack-plugin": "^5.2.0",
    "html-webpack-plugin-inject-thyme-leaf-tags": "^1.0.3",
    "mini-css-extract-plugin": "^2.5.3",
    "node-sass": "^7.0.1",
    "path": "^0.12.7",
    "postcss-loader": "^6.2.1",
    "sass-loader": "^12.4.0",
    "source-map-loader": "^3.0.1",
    "style-loader": "^2.0.0",
    "ts-loader": "^8.0.17",
    "ts-node": "^10.4.0",
    "typescript": "^4.5.5",
    "url-loader": "^4.1.1",
    "webpack": "^5.24.2",
    "webpack-bundle-analyzer": "^4.5.0",
    "webpack-cli": "^4.9.2",
    "webpack-dev-server": "^4.7.3"
  },
```

**Comment by sabipu** [comment] 2022-02-16 10:02
@cuongdevjs @adrienlamotte please fix the issue.

**Comment by anver** [comment] 2022-02-16 12:18
Removing type: "module" from package.json and building using yarn build will fix this error. I've a pull request here https://github.com/cuongdevjs/reactjs-social-login/pull/40  now it's a waiting game :)

**Comment by anver** [comment] 2022-02-16 13:42
> @cuongdevjs @adrienlamotte please let us know if we have fix for it, so that we can use the package properly.

check the above comment for the fix

**Comment by cuongdevjs** [comment] 2022-02-16 14:14
> > @cuongdevjs @adrienlamotte please let us know if we have fix for it, so that we can use the package properly.
> 
> check the above comment for the fix

Thank you. I'm gonna check it now

**Comment by cuongdevjs** [comment] 2022-02-16 16:21
@anver #40 merged. Thank you so much.

**Comment by anver** [comment] 2022-02-16 21:36
> @anver #40 merged. Thank you so much.

Hi @cuongdevjs pls check the latest PR. It will actually fix the exports issue for many people. This issue is caused by the microbundle-crl which generates only cjs builds. Thx

**Closed** 2022-05-22 05:01 UTC
Labels: dependencies
